app_theme <- function(type) {
  if (type == 'original') {
    theme <- list(v_content_bg_color = '#fcf5eb',
                  v_bg_color = '#FAEBD7',
                  v_font_color = '#3d3d3d',
                  v_active_input_color = '#3d3d3d',
                  v_inactive_input_color = '#8A837A',
                  v_graph_colors = cols <- c('#990000',
                                             '#996633',
                                             '#006600',
                                             '#000099'),
                  
                  vii_content_bg_color = '#fcf5eb',
                  vii_bg_color = '#FAEBD7',
                  vii_font_color = '#3d3d3d',
                  vii_active_input_color = '#3d3d3d',
                  vii_inactive_input_color = '#8A837A',
                  vii_graph_colors = cols <- c('#990000',
                                               '#006600',
                                               '#000099',
                                               '#650066',
                                               '#996633'),
                  font_family = 'Aldhabi',
                  font_size = 12)
  }
  
  if (type == 'green') {
    theme <- list(v_content_bg_color = '#fcf5eb',
                  v_bg_color = '#FAEBD7',
                  v_font_color = '#6A8157',
                  v_active_input_color = '#6A8157',
                  v_inactive_input_color = '#91B177',
                  v_graph_colors = cols <- c('#990000',
                                             '#996633',
                                             '#006600',
                                             '#000099'))
  }
  
  if (type == 'grey_turkus') {
    theme <- list(v_content_bg_color = '#EEF2F3',
                  v_bg_color = '#D7DBDB',
                  v_font_color = '#0E5E60',
                  v_active_input_color = '#0E5E60',
                  v_inactive_input_color = '#26A2A5',
                  v_graph_colors = cols <- c('#990000',
                                             '#996633',
                                             '#006600',
                                             '#000099'),
                  font_family = 'Aldhabi',
                  font_size = 12)
  }
  
  if (type == 'grey_orange') {
    theme <- list(v_content_bg_color = '#F3F1EE',
                  v_bg_color = '#DBDAD7',
                  v_font_color = '#60430E',
                  v_active_input_color = '#60430E',
                  v_inactive_input_color = '#A57E26',
                  v_graph_colors = cols <- c('#990000',
                                             '#996633',
                                             '#006600',
                                             '#000099'),
                  font_family = 'Aldhabi',
                  font_size = 12)
  }
  
  if (type == 'dark_orange') {
    theme <- list(v_content_bg_color = '#5B5A5A',
                  v_bg_color = '#3d3d3d',
                  v_font_color = '#FAEBD7',
                  v_active_input_color = '#FFAA54',
                  v_inactive_input_color = '#FFD8B2',
                  v_text_input_color = '#FFD8B2',
                  v_text_input_font_color = '#3d3d3d',
                  v_graph_colors = cols <- c('#FF5353',
                                             '#FFAA54',
                                             '#95FA95',
                                             '#8C8CFF'),
                  vii_content_bg_color = '#5B5A5A',
                  vii_bg_color = '#3d3d3d',
                  vii_font_color = '#FAEBD7',
                  vii_active_input_color = '#FFAA54',
                  vii_inactive_input_color = '#FFD8B2',
                  vii_text_input_color = '#FFD8B2',
                  vii_text_input_font_color = '#3d3d3d',
                  vii_graph_colors = cols <- c('#FE7F7F',
                                               '#95FA95',
                                               '#ABABFE',
                                               '#FCABFD',
                                               '#FFAA54'),

                  font_family = 'Aldhabi',
                  font_size = 12)
  }
  if (type == 'light_orange') {
    theme <- list(v_content_bg_color = '#fcf5eb',
                  v_bg_color = '#FAEBD7',
                  v_font_color = '#3d3d3d',
                  v_active_input_color = '#996633',
                  v_inactive_input_color = '#D68F48',
                  v_text_input_color = '#fcf5eb',
                  v_text_input_font_color = '#3d3d3d',
                  v_graph_colors = cols <- c('#990000',
                                             '#996633',
                                             '#006600',
                                             '#000099'),
                  
                  vii_content_bg_color = '#fcf5eb',
                  vii_bg_color = '#FAEBD7',
                  vii_font_color = '#3d3d3d',
                  vii_active_input_color = '#996633',
                  vii_inactive_input_color = '#D68F48',
                  vii_text_input_color = '#fcf5eb',
                  vii_text_input_font_color = '#3d3d3d',
                  vii_graph_colors = cols <- c('#990000',
                                               '#006600',
                                               '#000099',
                                               '#650066',
                                               '#996633'),
                  font_family = 'Aldhabi',
                  font_size = 12)
  }
  if (type == 'gender_app') {
    theme <- list(i_content_bg_color = '#fcf5eb',
                  i_bg_color = '#FAEBD7',
                  i_font_color = '#3d3d3d',
                  i_active_input_color = '#996633',
                  i_inactive_input_color = '#BD8B58',
                  i_text_input_color = '#fcf5eb',
                  i_text_input_font_color = '#3d3d3d',
                  i_graph_colors = cols <- c('#990000',
                                             '#996633',
                                             '#006600',
                                             '#000099'),
                  
                  ii_content_bg_color = '#5B5A5A',
                  ii_bg_color = '#3d3d3d',
                  ii_font_color = '#FAEBD7',
                  ii_active_input_color = '#FFAA54',
                  ii_inactive_input_color = '#FFD8B2',
                  ii_text_input_color = '#FFD8B2',
                  ii_text_input_font_color = '#3d3d3d',
                  ii_graph_colors = cols <- c('#FE7F7F',
                                               '#FFAA54',
                                               '#95FA95',
                                               '#ABABFE',
                                               '#FCABFD'),
                  
                  iii_content_bg_color = '#fcf5eb',  
                  iii_bg_color = '#FAEBD7',
                  iii_font_color = '#3d3d3d',
                  iii_active_input_color = '#996633',
                  iii_inactive_input_color = '#BD8B58',
                  iii_text_input_color = '#fcf5eb',  
                  iii_text_input_font_color = '#3d3d3d',
                  iii_graph_colors = cols <- c("#9292fe",
                                               "#FE7F7F",
                                               "#a6a6a6",
                                               "#95FA95"), 
                  
                  iv_content_bg_color = '#5B5A5A', 
                  iv_bg_color = '#3d3d3d', 
                  iv_font_color = '#FAEBD7',  
                  iv_active_input_color = '#FFAA54',  
                  iv_text_input_color = '#FFD8B2', 
                  iv_graph_colors = cols <- c("m" = "#9292fe",  
                                              "f" = "#FE7F7F",  
                                              "u" = "#a6a6a6", 
                                              "d" = "#95FA95"), 
                  
                  v_content_bg_color = '#fcf5eb',
                  v_bg_color = '#FAEBD7',
                  v_font_color = '#3d3d3d',
                  v_active_input_color = '#996633',
                  v_inactive_input_color = '#BD8B58',
                  v_text_input_color = '#fcf5eb',
                  v_text_input_font_color = '#3d3d3d',
                  v_graph_colors = cols <- c('#990000',
                                             '#996633',
                                             '#006600',
                                             '#000099'),
                  
                  vii_content_bg_color = '#5B5A5A',
                  vii_bg_color = '#3d3d3d',
                  vii_font_color = '#FAEBD7',
                  vii_active_input_color = '#FFAA54',
                  vii_inactive_input_color = '#FFD8B2',
                  vii_text_input_color = '#FFD8B2',
                  vii_text_input_font_color = '#3d3d3d',
                  vii_graph_colors = cols <- c('#FE7F7F',
                                               '#FFAA54',
                                               '#95FA95',
                                               '#ABABFE',
                                               '#FCABFD'),
                  
                  viii_content_bg_color = '#fcf5eb',
                  viii_bg_color = '#FAEBD7',
                  viii_font_color = '#3d3d3d',
                  viii_active_input_color = '#996633',
                  viii_inactive_input_color = '#BD8B58',
                  viii_text_input_color = '#fcf5eb',
                  viii_text_input_font_color = '#3d3d3d',
                  viii_graph_colors = cols <- c('#990000',
                                                '#996633',
                                                '#006600',
                                                '#000099'),
                  
                  font_family = 'Aldhabi',
                  font_size = 12)
  }

  return(theme)
}